#pragma once
#include <SFML/Graphics.hpp>
#include "game.h"
#include "soundManager.h"
#include "globals.h"
#include "configManager.h"


// ============ Auxiliar functions =============

// Adjusts the viewport (how the window sees the View) to maintain the aspect-ratio and center it
sf::FloatRect getCenteredViewport(float windowAspect, float viewAspect);


// ============ Game State Machine =============

// To avoid cyclic dependencies
class GameStateMachine;

class GameState{
protected:
    GameStateMachine* stateMachine;
    
public:
    sf::Vector2f m_viewSize;
    explicit GameState(GameStateMachine* stateMachine) : stateMachine(stateMachine) {}
    virtual ~GameState() = default;

    // Method that's called when a state is newly started
    // and initializes everything the state needs
    virtual void init() = 0;

    // Method that manages the input events generated by the user
    virtual void handleInput(sf::Event event) = 0;

    // Method that manages the game logic every frame
    virtual void update(float deltaTime, const sf::View& view) = 0;

    // Method that displays the game graphics onto the <window>
    virtual void draw(sf::RenderWindow& window, Camera& camera) = 0;

    // Method that is called when it's overtaken by other.
    // Pauses animations, sounds, ...
    virtual void pause(){}

    // Method that is called when it returns to the top of the stack
    // Resumes animations, sounds, ...
    virtual void resume(){}

    // Method that is called when the state is terminated, it is mainly used for
    // erasing unused variables and freeing storage
    virtual void close(){}

    // Function that returns the camera's view
    virtual sf::View getView(sf::RenderWindow& window, Camera& camera);
};


class GameGS : public GameState{
public:
    Game game;

    explicit GameGS(GameStateMachine* machine) : GameState(machine), game() {}
    ~GameGS() override;
    void init() override;
    void handleInput(sf::Event event) override;
    void update(float deltaTime, const sf::View& view) override;
    void draw(sf::RenderWindow& window, Camera& camera) override;
    void pause() override;
    void resume() override;
    void close() override;
    sf::View getView(sf::RenderWindow& window, Camera& camera) override;
};


class MenuGS : public GameState{
private:
    // std::unordered_map<std::string, sf::Texture> menuTextures;
    // std::vector<sf::Sprite> menuSprites;
    sf::Font font;
    std::vector<sf::Text> options;
    int position;
    SoundManager menuSoundManager;
    configManager &configManager;
public:
    explicit MenuGS(GameStateMachine* machine) : GameState(machine), configManager(configManager::getInstance()) {}
    ~MenuGS() override;
    void init() override;
    void handleInput(sf::Event event) override;
    void update(float deltaTime, const sf::View& view) override;
    void draw(sf::RenderWindow& window, Camera& camera) override;
    void pause() override;
    void resume() override;
    void close() override;
    sf::View getView(sf::RenderWindow& window, Camera& camera) override;
};


class PauseGS : public GameState{
public:
    explicit PauseGS(GameStateMachine* machine) : GameState(machine) {}
    ~PauseGS() override;
    void init() override;
    void handleInput(sf::Event event) override;
    void update(float deltaTime, const sf::View& view) override;
    void draw(sf::RenderWindow& window, Camera& camera) override;
    void pause() override;
    void resume() override;
    void close() override;
};


class ConfigGS : public GameState{
private:
    sf::Font font;
    std::vector<sf::Text> configs;
    int position;
    SoundManager configSoundManager;
    configManager &configManager;
public:
    explicit ConfigGS(GameStateMachine* machine) : GameState(machine), configManager(configManager::getInstance()) {}
    ~ConfigGS() override;
    void init() override;
    void handleInput(sf::Event event) override;
    void update(float deltaTime, const sf::View& view) override;
    void draw(sf::RenderWindow& window, Camera& camera) override;
    void pause() override;
    void resume() override;
    void close() override;
};


// ADD THE REST OF THE STATES HERE