#pragma once
#include <SFML/Graphics.hpp>
#include "game.h"
#include "soundManager.h"
#include "globals.h"
#include "configManager.h"
#include <string>


// ============ Auxiliar functions =============

// Adjusts the viewport (how the window sees the View) to maintain the aspect-ratio and center it
sf::FloatRect getCenteredViewport(float windowAspect, float viewAspect);


// ============ Game State Machine =============

// To avoid cyclic dependencies
class GameStateMachine;

class GameState{
protected:
    GameStateMachine* stateMachine;
    
public:
    sf::Vector2f m_viewSize;
    explicit GameState(GameStateMachine* stateMachine) : stateMachine(stateMachine) {}
    virtual ~GameState() = default;

    // Method that's called when a state is newly started
    // and initializes everything the state needs
    virtual void init() = 0;

    // Method that manages the input events generated by the user
    virtual void handleInput(sf::Event event) = 0;

    // Method that manages the game logic every frame
    virtual void update(float deltaTime, const sf::Vector2f& viewPosition) = 0;

    // Method that displays the game graphics onto the <window>
    virtual void draw(sf::RenderWindow& window, Camera& camera) = 0;

    // Method that is called when it's overtaken by other.
    // Pauses animations, sounds, ...
    virtual void pause(){}

    // Method that is called when it returns to the top of the stack
    // Resumes animations, sounds, ...
    virtual void resume(){}

    // Method that is called when the state is terminated, it is mainly used for
    // erasing unused variables and freeing storage
    virtual void close(){}

    // Function that returns the camera's view
    virtual sf::View getView(sf::RenderWindow& window, Camera& camera);
};


class GameGS : public GameState{
public:
    Game game;

    explicit GameGS(GameStateMachine* machine) : GameState(machine), game() {}
    ~GameGS() override;
    void init() override;
    void handleInput(sf::Event event) override;
    void update(float deltaTime, const sf::Vector2f& viewPosition) override;
    void draw(sf::RenderWindow& window, Camera& camera) override;
    void pause() override;
    void resume() override;
    void close() override;
    sf::View getView(sf::RenderWindow& window, Camera& camera) override;
};


class walkingAnimGS : public GameState{
private:
    SoundManager walkingAnimSoundManager;
    configManager &configManager;
    sf::Font font;
    std::vector<sf::Text> texts;
    std::vector<sf::Vector2f> textPositions;
    // AnimationManager *bat1{nullptr};
    // std::shared_ptr<sf::Sprite> bat1;
    // AnimationManager *bat2{nullptr};
    // std::shared_ptr<sf::Sprite> bat2;
    AnimationManager *simonManager{nullptr};
    std::shared_ptr<sf::Sprite> simon;
    // AnimationManager *cloud{nullptr};
    // std::shared_ptr<sf::Sprite> cloud;
public:
    explicit walkingAnimGS(GameStateMachine* machine) : GameState(machine), configManager(configManager::getInstance()) {}
    ~walkingAnimGS() override;
    void init() override;
    void handleInput(sf::Event event) override;
    void update(float deltaTime, const sf::Vector2f& viewPosition) override;
    void draw(sf::RenderWindow& window, Camera& camera) override;
    void drawHealthBars(sf::RenderWindow &window, int health, int bossHealth,
        sf::Vector2f virtualWorldset);
    void pause() override;
    void resume() override;
    void close() override;
};


class MenuGS : public GameState{
private:
    sf::Font font;
    std::vector<sf::Text> options;
    int position;
    SoundManager menuSoundManager;
    configManager &configManager;
    bool exit;
    float timeOut = 0.0f;
    float timeInterval = 30.f;
public:
    explicit MenuGS(GameStateMachine* machine) : GameState(machine), configManager(configManager::getInstance()) {}
    ~MenuGS() override;
    void init() override;
    void handleInput(sf::Event event) override;
    void update(float deltaTime, const sf::Vector2f& viewPosition) override;
    void draw(sf::RenderWindow& window, Camera& camera) override;
    void pause() override;
    void resume() override;
    void close() override;
    sf::View getView(sf::RenderWindow& window, Camera& camera) override;
};


class PauseGS : public GameState{
public:
    explicit PauseGS(GameStateMachine* machine) : GameState(machine) {}
    ~PauseGS() override;
    void init() override;
    void handleInput(sf::Event event) override;
    void update(float deltaTime, const sf::Vector2f& viewPosition) override;
    void draw(sf::RenderWindow& window, Camera& camera) override;
    void pause() override;
    void resume() override;
    void close() override;
};


class ConfigGS : public GameState{
private:
    sf::Font font;
    std::vector<sf::Text> configs;
    int position;
    SoundManager configSoundManager;
    configManager &configManager;
public:
    explicit ConfigGS(GameStateMachine* machine) : GameState(machine), configManager(configManager::getInstance()) {}
    ~ConfigGS() override;
    void init() override;
    void handleInput(sf::Event event) override;
    void update(float deltaTime, const sf::Vector2f& viewPosition) override;
    void draw(sf::RenderWindow& window, Camera& camera) override;
    void pause() override;
    void resume() override;
    void close() override;
};


class ControlsConfGS : public GameState{
private:
    sf::Font font, fontinputs;
    std::vector<sf::Text> configs;
    int position, col;
    SoundManager configControlsManager;
    configManager &configManager;
    std::string right, left, down, up, jump, attack, enter, escape, useSubWeapon;
    std::string defRight, defLeft, defDown, defUp, defJump, defAttack, defEnter, defEscape, defUseSubWeapon;
    bool waitingInput, showPopUp;
    float popUpTimer = 0.0;
    float popUpInterval = 3.5;
    float blinkTimer = 0.0;
    float blinkInterval = 0.25;
public:
    explicit ControlsConfGS(GameStateMachine* machine) : GameState(machine), configManager(configManager::getInstance()) {}
    ~ControlsConfGS() override;
    void init() override;
    void setDefault();
    bool checkInputErrors();
    void handleInput(sf::Event event) override;
    void update(float deltaTime, const sf::Vector2f& viewPosition) override;
    void draw(sf::RenderWindow& window, Camera& camera) override;
    void pause() override;
    void resume() override;
    void close() override;
};


class VolumeConfGS : public GameState{
private:
    sf::Font font;
    std::vector<sf::Text> configs;
    int position, col;
    SoundManager configVolumeManager;
    configManager &configManager;
    int masterVol, musicVol, soundVol;
public:
    explicit VolumeConfGS(GameStateMachine* machine) : GameState(machine), configManager(configManager::getInstance()) {}
    ~VolumeConfGS() override;
    void init() override;
    void handleInput(sf::Event event) override;
    void update(float deltaTime, const sf::Vector2f& viewPosition) override;
    void drawVolumeBars(sf::RenderWindow& window, int actualVol, sf::Vector2f pos);
    void draw(sf::RenderWindow& window, Camera& camera) override;
    void pause() override;
    void resume() override;
    void close() override;
};


class GameplayConfGS : public GameState{
private:
    sf::Font font, fontinputs;
    std::vector<sf::Text> configs;
    int position, col;
    SoundManager configGameplayManager;
    configManager &configManager;
    bool video, difficulty, cheats;
public:
    explicit GameplayConfGS(GameStateMachine* machine) : GameState(machine), configManager(configManager::getInstance()) {}
    ~GameplayConfGS() override;
    void init() override;
    void handleInput(sf::Event event) override;
    void update(float deltaTime, const sf::Vector2f& viewPosition) override;
    void draw(sf::RenderWindow& window, Camera& camera) override;
    void pause() override;
    void resume() override;
    void close() override;
};


class InitMenuGS : public GameState{
private:
    SoundManager menuSoundManager;
    configManager &configManager;
    AnimationManager *animationManager{nullptr};
    std::shared_ptr<sf::Sprite> castle;
    bool blinking;
    int blinks, maxBlinks;
    float blinkTimer = 0.0;
    float blinkInterval = 0.2f;
public:
    explicit InitMenuGS(GameStateMachine* machine) : GameState(machine), configManager(configManager::getInstance()) {}
    ~InitMenuGS() override;
    void init() override;
    void handleInput(sf::Event event) override;
    void update(float deltaTime, const sf::Vector2f& viewPosition) override;
    void draw(sf::RenderWindow& window, Camera& camera) override;
    void pause() override;
    void resume() override;
    void close() override;
};


class InitAnimationGS : public GameState{
private:
    SoundManager initAnimSounds;
    configManager &configManager;
    sf::Font font;
    std::vector<sf::Text> warning;
    int slide;
    float timer = 0.0f;
    float timerInterval = 9.0f;
    bool fadingOutMusic;
    float currentMusicVolume;
    float fadeOutSpeed;
public:
    explicit InitAnimationGS(GameStateMachine* machine) : GameState(machine), configManager(configManager::getInstance()) {}
    ~InitAnimationGS() override;
    void init() override;
    void handleInput(sf::Event event) override;
    void update(float deltaTime, const sf::Vector2f& viewPosition) override;
    void draw(sf::RenderWindow& window, Camera& camera) override;
    void drawSlide(sf::RenderWindow& window);
    void resetMovingSprites();
    void pause() override;
    void resume() override;
    void close() override;
};