name: Build C++ Project

on:
  push:
    branches:
      - 'main'  # Ejecutar en cada push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MinGW (g++)
        run: |
          choco install mingw -y
          echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $env:GITHUB_PATH

      - name: Set up SFML
        run: |
          mkdir C:\SFML
          xcopy /E /I SFML\* C:\SFML

      - name: Create build subdirectories
        run: |
          if (!(Test-Path -Path "build")) { New-Item -ItemType Directory -Path "build" }
          if (!(Test-Path -Path "build/enemies")) { New-Item -ItemType Directory -Path "build/enemies" }

      - name: Build project with make
        run: make

      - name: Prepare dist folder
        shell: cmd
        run: |
          mkdir dist
          copy build\game.exe dist\
          for %%f in (build\*.dll) do copy %%f dist\
          xcopy /E /I assets dist\assets\
          copy config.json dist\

      - name: Zip build folder
        run: powershell Compress-Archive -Path dist\* -DestinationPath Castlevania.zip

      - name: Create tag for release
        run: |
          # Crear una nueva etiqueta basada en el número de ejecución
          git tag -a "v${{ github.run_number }}" -m "Release v${{ github.run_number }}"
          git push origin "v${{ github.run_number }}"

      - name: Create release and upload zip
        uses: softprops/action-gh-release@v1
        with:
          files: Castlevania.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
