name: Build C++ Project

on:
  push:
    branches:
      - '**'  # En cada push a cualquier rama

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set up SFML
        run: |
          mkdir C:\SFML
          xcopy /E /I SFML\* C:\SFML

      - name: Build with make
        run: |
          make

      - name: Package build
        run: |
          mkdir dist
          copy build\*.exe dist\
          copy build\*.dll dist\
          xcopy /E /I assets dist\assets\
          copy config.json dist\

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: game-build
          path: dist
